version: "3"

services:
      consumer:
            image: service-consumer
            container_name: consumer
            ports:
            - "9091:9091"
            networks:
              - consumer-producer
            depends_on:
              - producer
      producer:
           image: service-producer
           container_name: producer
           ports:
           - "9090:9090"
           networks:
            - consumer-producer

networks:
  consumer-producer:
